#!/bin/sh

command="$1"

START=90
INTERFACE=br0
PORT=1337

# check if configuration exists
[ -e "/opt/etc/redsocks.conf" ] || exit 0

iptable_start() {
    /bin/echo -n "running REDSOCKS iptables ..."

    # Run iptable commands
    iptables -t nat -N REDSOCKS

    iptables -t nat -A REDSOCKS -d 0.0.0.0/8 -j RETURN
    iptables -t nat -A REDSOCKS -d 10.0.0.0/8 -j RETURN
    iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN
    iptables -t nat -A REDSOCKS -d 169.254.0.0/16 -j RETURN
#    iptables -t nat -A REDSOCKS -d 172.16.0.0/12 -j RETURN
    iptables -t nat -A REDSOCKS -d 192.168.0.0/16 -j RETURN
    iptables -t nat -A REDSOCKS -d 224.0.0.0/4 -j RETURN
    iptables -t nat -A REDSOCKS -d 240.0.0.0/4 -j RETURN

    iptables -t nat -A REDSOCKS -p tcp -j REDIRECT --to-ports ${PORT}

    iptables -t nat -A PREROUTING -i ${INTERFACE} -p tcp -j REDSOCKS

    iptables -A INPUT -i ${INTERFACE} -p tcp --dport ${PORT} -j ACCEPT

    /bin/echo " done"
}

iptable_stop() {
    /bin/echo -n "cleaning REDSOCKS iptables ..."

    # Run iptable commands
    iptables -t nat -F REDSOCKS
    iptables -t nat -F PREROUTING
    iptables -t nat -F POSTROUTING
    iptables -F INPUT
    iptables -F FORWARD
    iptables -t nat -X REDSOCKS

    /bin/echo " done"
}

start() {
    if [ -e "/opt/var/run/redsocks.pid" ]; then
        echo "bdix is already running"
        exit 0
    fi

    /bin/echo -n "running REDSOCKS ..."

    # startup the safety-wrapper for the daemon
    /opt/sbin/redsocks -c /opt/etc/redsocks.conf -p /opt/var/run/redsocks.pid

    /bin/echo " done"
    iptable_start
}


stop() {
    if [ ! -e "/opt/var/run/redsocks.pid" ]; then
        echo "REDSOCKS is not running"
        exit 0
    fi

    /bin/echo -n "stopping REDSOCKS ..."

    # kill the process
    /bin/kill $(cat /opt/var/run/redsocks.pid)
    rm /opt/var/run/redsocks.pid

    echo " done"
    iptable_stop

    /bin/echo -n "restarting firewall ..."
    service restart_firewall &> /dev/null
    /bin/echo " done"
}

if [ $command == "start" ]; then
    start
elif [ $command == "stop" ]; then
    stop
elif [ $command == "restart" ]; then
    stop
    start
else
    echo "Usage: $0 {start|stop|restart}"
fi